# WebLoginBrute 配置文件示例
# 复制此文件为 config.yaml 并根据需要修改

# 必需参数
form: "https://example.com/login"           # 登录表单URL
submit: "https://example.com/login"         # 登录提交URL
users: "wordlists/users.txt"                # 用户名字典文件
passwords: "wordlists/passwords.txt"        # 密码字典文件

# 可选参数
csrf: "csrf_token"                          # CSRF token字段名（如目标无CSRF token可省略）
field: "remember"                           # 额外的登录字段名
value: "1"                                  # 额外的登录字段值
cookies: "cookies.txt"                      # Cookie文件路径
timeout: 30                                 # 请求超时时间（秒）
threads: 5                                  # 并发线程数
resume: false                               # 从上次中断的地方继续
progress: "bruteforce_progress.json"        # 进度文件路径
level: "A1"                                 # 对抗级别（A0=静默，A1=标准，A2=激进，A3=极限）
dry_run: false                              # 测试模式，不实际发送请求
verbose: false                              # 详细输出

# --- 安全配置 (通常不需要修改) ---
# 以下配置用于增强安全性，如需覆盖默认值，可在此处定义
# ip_whitelist: ["192.168.1.0/24"]             # IP白名单 (CIDR格式)
# ip_blacklist: ["10.0.0.1"]                  # IP黑名单
