# WebLoginBrute v0.27.9 配置文件示例
# 复制此文件为 config.yaml 并根据需要修改

# ⚠️ 切勿将真实密码、cookie等敏感信息直接写入此文件！
# 建议将敏感信息通过安全方式管理，如环境变量或专用密钥管理系统。

# 必需参数
url: "https://redteamnotes.com/login"                    # 登录表单页面URL
action: "https://redteamnotes.com/login/authenticate"    # 登录表单提交URL
users: "wordlists/users.txt"                       # 用户名字典文件
passwords: "wordlists/passwords.txt"               # 密码字典文件

# 结果判断参数 (至少需要一个)
success_string: "Welcome"
fail_string: "Invalid credentials"
# success_redirect: "https://redteamnotes.com/dashboard"
# failure_redirect: "https://redteamnotes.com/login?error=1"

# 可选参数
csrf: "csrf_token"                                 # CSRF token字段名（如目标无CSRF token可省略）
login_field: "domain"                              # 额外的登录字段名（可选）
login_value: "redteamnotes.com"                    # 额外的登录字段值（可选）
cookie: "cookies.txt"                              # Cookie文件路径（可选）

# 性能配置
threads: 5                                         # 并发线程数 (1-100)
timeout: 30                                        # 请求超时时间（秒）
aggressive: 1                                   # 对抗级别: 0(静默) 1(标准) 2(激进) 3(极限)

# 进度管理
resume: false                                      # 是否从上次中断的地方继续
log: "bruteforce_progress.json"                    # 进度文件路径

# 输出控制
verbose: false                                     # 详细输出模式
dry_run: false                                     # 测试模式，不实际发送请求

# 高级配置（可选）
# max_retries: 3                                   # 最大重试次数
# base_delay: 1.0                                  # 基础延迟时间（秒）

# 内存管理配置（新增）
# max_memory_mb: 500                              # 最大内存使用量(MB)
# memory_warning_threshold: 0.8                   # 内存警告阈值(80%)
# memory_critical_threshold: 0.9                  # 内存临界阈值(90%)
# memory_cleanup_interval: 60                     # 内存清理间隔(秒)

# 会话管理配置（新增）
# session_rotation_interval: 300                  # 会话轮换间隔(秒)
# session_lifetime: 600                           # 会话生命周期(秒)
# max_session_pool_size: 100                      # 最大会话池大小
# enable_session_rotation: true                   # 是否启用会话轮换
# rotation_strategy: "time"                       # 轮换策略: time, request_count, error_rate

# 安全配置（可选）
# ip_whitelist: ["192.168.1.0/24"]                # IP白名单
# ip_blacklist: ["10.0.0.1"]                      # IP黑名单
